# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
#  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  # jinhuang（默认）
  default:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "654321"
    name: "jinhuang"
    timezone: "Local"
#    link: "mysql:root:654321@tcp(127.0.0.1:3306)/jinhuang"
    debug: true
    charset: "utf8mb4"
  # jh_site
  jh_site:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "654321"
    name: "jh_site"
    timezone: "Local"
#    link: "mysql:root:654321@tcp(127.0.0.1:3306)/jh_site"
    debug: true
    charset: "utf8mb4"
  # jh_balance
  jh_balance:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "654321"
    name: "jh_balance"
    timezone: "Local"
#    link: "mysql:root:654321@tcp(127.0.0.1:3306)/jh_balance"
    debug: true
    charset: "utf8mb4"
  # jh_game
  jh_game:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "654321"
    name: "jh_game"
    timezone: "Local"
#    link: "mysql:root:654321@tcp(127.0.0.1:3306)/jh_game"
    debug: true
    charset: "utf8mb4"
jwt:
  secret: "7kPApNTrloUHNS29bLWbexySu2381X6P"
  expire: 86400   # token有效期 1天