
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      # jinhuang（默认）
      - link: "mysql:root:654321@tcp(127.0.0.1:3306)/jinhuang"
        path: "internal/dao/jinhuang"
        group: "default"                  # GoFrame中对应的group名
        descriptionTag: true
        jsonCase: "SnakeLower"            # JSON字段命名规则
        overwrite: true                   # 是否覆盖生成文件
      # jh_site
      - link: "mysql:root:654321@tcp(127.0.0.1:3306)/jh_site"
        path: "internal/dao/jh_site"
        group: "jh_site"                  # GoFrame中对应的group名
        descriptionTag: true
        jsonCase: "SnakeLower"            # JSON字段命名规则
        overwrite: true                   # 是否覆盖生成文件
      # jh_balance
      - link: "mysql:root:654321@tcp(127.0.0.1:3306)/jh_balance"
        path: "internal/dao/jh_balance"
        group: "jh_balance"                  # GoFrame中对应的group名
        descriptionTag: true
        jsonCase: "SnakeLower"            # JSON字段命名规则
        overwrite: true                   # 是否覆盖生成文件
      # jh_game
      - link: "mysql:root:654321@tcp(127.0.0.1:3306)/jh_game"
        path: "internal/dao/jh_game"
        group: "jh_game"                  # GoFrame中对应的group名
        descriptionTag: true
        jsonCase: "SnakeLower"            # JSON字段命名规则
        overwrite: true                   # 是否覆盖生成文件


  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app